// Generated by CoffeeScript 1.9.1
(function() {
  var index;

  index = require('./index.js');

  index.run({
    outLogFile: "/tmp/out",
    errLogFile: "/tmp/err"
  }, function() {
    return console.log(index.options);
  });

}).call(this);

//# sourceMappingURL=test.js.map
